In [3]:

import pandas as pd

ratings = {
    "Movie": [
        "Barbie",
        "Oppenheimer",
        "Dune: Part Two",
        "Wicked",
        "Sinners",
        "Obsession"
    ],
    "Alyssa": [5, 4, 3, 5, 5, 4],
    "Sarah": [4, 5, 4, 5, 4, None],
    "Michael": [3, 5, 5, 3, 5, 4],
    "Jessica": [5, 3, None, 5, 4, 5],
    "Daniel": [4, 5, 5, 4, None, 3]
}

df = pd.DataFrame(ratings)
df.set_index("Movie", inplace=True)

df

                Alyssa  Sarah  Michael  Jessica  Daniel
Movie
Barbie               5    4.0        3      5.0     4.0
Oppenheimer          4    5.0        5      3.0     5.0
Dune: Part Two       3    4.0        5      NaN     5.0
Wicked               5    5.0        3      5.0     4.0
Sinners              5    4.0        5      4.0     NaN
Obsession            4    NaN        4      5.0     3.0

In [4]:

# Save movie ratings to a CSV file
df.to_csv("movie_ratings.csv")

# Load the CSV file into a new DataFrame
movie_ratings = pd.read_csv("movie_ratings.csv", index_col="Movie")

# Display the ratings
movie_ratings

                Alyssa  Sarah  Michael  Jessica  Daniel
Movie
Barbie               5    4.0        3      5.0     4.0
Oppenheimer          4    5.0        5      3.0     5.0
Dune: Part Two       3    4.0        5      NaN     5.0
Wicked               5    5.0        3      5.0     4.0
Sinners              5    4.0        5      4.0     NaN
Obsession            4    NaN        4      5.0     3.0

In [3]:

# Calculate average rating for each person
user_averages = movie_ratings.mean(axis=0)

print("Average Rating by Person:")
print(user_averages.round(2))

# Calculate average rating for each movie
movie_averages = movie_ratings.mean(axis=1)

print("\nAverage Rating by Movie:")
print(movie_averages.round(2))

Average Rating by Person:
Alyssa     4.33
Sarah      4.40
Michael    4.17
Jessica    4.40
Daniel     4.20
dtype: float64

Average Rating by Movie:
Movie
Barbie            4.20
Oppenheimer       4.40
Dune: Part Two    4.25
Wicked            4.40
Sinners           4.50
Obsession         4.00
dtype: float64

In [4]:

# Normalize ratings for each person (0 to 1 scale)
normalized_ratings = (movie_ratings - movie_ratings.min()) / (movie_ratings.max() - movie_ratings.min())

# Display normalized ratings
print("Normalized Movie Ratings:")
display(normalized_ratings.round(2))

# Calculate average normalized rating for each person
print("Average Normalized Rating by Person:")
print(normalized_ratings.mean(axis=0).round(2))

# Calculate average normalized rating for each movie
print("\nAverage Normalized Rating by Movie:")
print(normalized_ratings.mean(axis=1).round(2))

Normalized Movie Ratings:

                Alyssa  Sarah  Michael  Jessica  Daniel
Movie
Barbie             1.0    0.0      0.0      1.0     0.5
Oppenheimer        0.5    1.0      1.0      0.0     1.0
Dune: Part Two     0.0    0.0      1.0      NaN     1.0
Wicked             1.0    1.0      0.0      1.0     0.5
Sinners            1.0    0.0      1.0      0.5     NaN
Obsession          0.5    NaN      0.5      1.0     0.0

Average Normalized Rating by Person:
Alyssa     0.67
Sarah      0.40
Michael    0.58
Jessica    0.70
Daniel     0.60
dtype: float64

Average Normalized Rating by Movie:
Movie
Barbie            0.50
Oppenheimer       0.70
Dune: Part Two    0.50
Wicked            0.70
Sinners           0.62
Obsession         0.50
dtype: float64

### Conclusion

Normalizing movie ratings makes it easier to compare how different people rate movies. Some people might give almost every movie a high rating, while others are more critical. Normalization puts everyone's ratings on the same scale from 0 to 1, which helps show their preferences compared to their other ratings.

One advantage is that it makes comparisons between people more consistent. However, a disadvantage is that we lose some of the original rating information. For example, someone who gives a movie a 3 might end up with a similar normalized score as someone who gave it a 5, depending on their other ratings.

Overall, I think normalized ratings are useful when comparing people's preferences, but actual ratings are better when you want to see how much someone liked a movie on the original scale.

In [5]:

import pandas as pd

movie_ratings = pd.read_csv("movie_ratings.csv", index_col="Movie")

display(movie_ratings)


# Standardize ratings for each person using z-scores
standardized_ratings = (
    movie_ratings - movie_ratings.mean()
) / movie_ratings.std()

# Display standardized ratings
print("Standardized Movie Ratings:")
display(standardized_ratings.round(2))

# Calculate average standardized rating for each person
print("Average Standardized Rating by Person:")
print(standardized_ratings.mean(axis=0).round(2))

# Calculate average standardized rating for each movie
print("\nAverage Standardized Rating by Movie:")
print(standardized_ratings.mean(axis=1).round(2))

                Alyssa  Sarah  Michael  Jessica  Daniel
Movie
Barbie               5    4.0        3      5.0     4.0
Oppenheimer          4    5.0        5      3.0     5.0
Dune: Part Two       3    4.0        5      NaN     5.0
Wicked               5    5.0        3      5.0     4.0
Sinners              5    4.0        5      4.0     NaN
Obsession            4    NaN        4      5.0     3.0

Standardized Movie Ratings:

                Alyssa  Sarah  Michael  Jessica  Daniel
Movie
Barbie            0.82  -0.73    -1.19     0.67   -0.24
Oppenheimer      -0.41   1.10     0.85    -1.57    0.96
Dune: Part Two   -1.63  -0.73     0.85      NaN    0.96
Wicked            0.82   1.10    -1.19     0.67   -0.24
Sinners           0.82  -0.73     0.85    -0.45     NaN
Obsession        -0.41    NaN    -0.17     0.67   -1.43

Average Standardized Rating by Person:
Alyssa     0.0
Sarah     -0.0
Michael   -0.0
Jessica   -0.0
Daniel    -0.0
dtype: float64

Average Standardized Rating by Movie:
Movie
Barbie           -0.13
Oppenheimer       0.19
Dune: Part Two   -0.14
Wicked            0.23
Sinners           0.12
Obsession        -0.34
dtype: float64